### ISSUE TITLE
Non default SSH port

### ISSUE THREAD

**Issue by jmrplens** [pixta-dev/repository-mirroring-action#29]
How can I define a port other than port 22?

On my server I use another port for ssh access.

Thanks

**Comment by 5ika** [comment]
You can use a 'SSH URL style' instead of SCP style.

See https://stackoverflow.com/questions/1558719/using-a-remote-repository-with-non-standard-port

**Comment by yasaichi** [comment]
@5ika 
Thanks for your help. Closing the issue.
